### ISSUE TITLE
El session_start se repite mucho

### ISSUE THREAD

**Issue by julianbutti** [LeonardoCristalli/Concursos_Docente#1]
Si es algo transversal a la mayoría, convendría iniciar sesion, por más de que no se use o no haga falta.
Sinó estás repitiendo el inicio en infinidad de funciones.
Podría estar en el core, o en el redireccionador

https://github.com/LeonardoCristalli/Concursos_Docente/blob/e604b7bfa9b9ef1bfc567d8e725d4f98f29b29a0/app/controladores/Paginas.php#L40

**Comment by LeonardoCristalli** [comment]
claro pero pense que era incorrecto hacerlo antes del login, como sabia que si estaba la session activa, el session start se desestimaba, pero entiendo, total el login se corresponde con la asignacion de laa variable de sesión usuario_id. Lo movi al iniciador. Gracias por las devoluciones
