### ISSUE TITLE
Las carpetas de uploads deberian ser privadas, o a lo sumo tener un htaccess para q no se pueda listar o acceder a archivos sin permisos

### ISSUE THREAD

**Issue by julianbutti** [LeonardoCristalli/Concursos_Docente#7]
https://github.com/LeonardoCristalli/Concursos_Docente/blob/e604b7bfa9b9ef1bfc567d8e725d4f98f29b29a0/app/controladores/UsuarioController.php#L64

**Comment by LeonardoCristalli** [comment]
Moví uploads de public a app, que tiene un htaccess Options -Indexes que evita que el contenido del directorio se pueda listar. Se actualizaron los métodos en los controladorese correspondientes (Paginas, UsuarioController)

**Comment by LeonardoCristalli** [comment]
Agregado de htaccess dentro de carpeta uploads, agregado de verificación de permisos en método descargarCV de UsuarioController
